### ISSUE TITLE
Hint about your message: MSBUILD : error MSB1009: Project file does not exist.

### ISSUE THREAD

**Issue by aismann** [Diam2023/MyLittleAxmolGameDemo#1]
```
MSBuild version 17.9.5+33de0b227 for .NET Framework
MSBUILD : error MSB1009: Project file does not exist.
Switch: MyLittleAxmolGameDemo-main.vcxproj
```
You have renamed the folder:   `MyGameDemo `to  `MyLittleAxmolGameDemo`

works here:
![image](https://github.com/Diam2023/MyLittleAxmolGameDemo/assets/8652787/1327829a-3621-42c3-bf32-a933196e9073)

**Comment by Diam2023** [comment]
Oh... Thank you again
I got It
